name: mujoco_vla
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libblas=3.9.0=35_h4a7cf45_openblas
  - libcblas=3.9.0=35_h0358290_openblas
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgomp=15.1.0=h767d61c_5
  - liblapack=3.9.0=35_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libuuid=2.41.1=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - numpy=2.2.6=py310hefbff90_0
  - openssl=3.5.2=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - python_abi=3.10=8_cp310
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==15.1.0
      - blinker==1.9.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cloudpickle==3.1.1
      - cmake==4.1.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.6.0
      - deepdiff==8.6.1
      - diffusers==0.35.1
      - dill==0.3.8
      - docopt==0.6.2
      - draccus==0.10.0
      - einops==0.8.1
      - etils==1.13.0
      - evdev==1.9.2
      - farama-notifications==0.0.4
      - flask==3.1.2
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.9.0
      - gymnasium==0.29.1
      - hf-transfer==0.1.9
      - hf-xet==1.1.9
      - huggingface-hub==0.34.4
      - idna==3.10
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - inquirerpy==0.3.4
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jsonlines==4.0.0
      - kiwisolver==1.4.9
      - lerobot==0.3.4
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mergedeep==1.3.4
      - mouseinfo==0.1.3
      - mujoco==3.1.6
      - multidict==6.6.4
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - num2words==0.5.14
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orderly-set==5.5.0
      - pandas==2.3.2
      - pfzy==0.3.4
      - pillow==11.3.0
      - pluggy==1.6.0
      - propcache==0.3.2
      - protobuf==6.32.0
      - pyarrow==21.0.0
      - pyautogui==0.9.54
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygetwindow==0.0.9
      - pymsgbox==2.0.1
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.2.3
      - pyperclip==1.9.0
      - pyrect==0.2.0
      - pyscreeze==1.0.1
      - pyserial==3.5
      - pytest==8.4.2
      - python-xlib==0.33
      - python3-xlib==0.15
      - pytweening==1.2.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyyaml-include==1.4.1
      - regex==2025.9.1
      - requests==2.32.5
      - rerun-sdk==0.22.1
      - safetensors==0.6.2
      - scipy==1.15.3
      - sentry-sdk==2.37.1
      - smmap==5.0.2
      - sympy==1.14.0
      - termcolor==3.1.0
      - tokenizers==0.21.4
      - toml==0.10.2
      - torch==2.7.1
      - torchcodec==0.5
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.50.3
      - triton==3.3.1
      - typeguard==4.4.4
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.21.3
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /home/dragon/anaconda3/envs/mujoco_vla
